version: '3'

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 5422:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .waves2:/var/lib/postgresql/data
  waves:
    build: .
    image: deflorator1980/waves2
#    command: sh run.sh
    command: java -jar waves-1.jar
    network_mode: "host"
    ports:
      - 8080:8080
    environment:
      PGHOST: db
    depends_on:
      - db
